services:
  db:
    image: mysql:latest
    container_name: socketio
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tchat
      MYSQL_USER: me
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
